//
//  AvailabilitySlot.swift
//  AthleticsPerformance
//
//  Created by Frank Ufer on 16.04.25.
//

import Foundation

struct AvailabilitySlotFile: Codable {
    var version: Int
    var items: [AvailabilitySlot]
}

/// Represents a time slot indicating when a resource or person is available.
struct AvailabilitySlot: Codable, Identifiable, Hashable {
    /// Unique identifier for the availability slot.
    var id: UUID

    /// Start date and time of the availability period.
    var start: Date

    /// End date and time of the availability period.
    var end: Date

    /// Type of availability (available, vacation, training, blocked).
    var type: AvailabilityType

    /// Optional note or comment for this entry.
    var note: String?

    /// Optional source information (e.g., manually created, generated by rule).
    var source: AvailabilitySource?

    /// Initializes a new `AvailabilitySlot` with the given start and end times.
    /// - Parameters:
    ///   - id: Unique identifier for the slot (default is a new UUID).
    ///   - start: Start date and time.
    ///   - end: End date and time.
    ///   - type: Availability type (default: .available).
    ///   - note: Optional note.
    ///   - source: Optional source.
    init(
        id: UUID = UUID(),
        start: Date,
        end: Date,
        type: AvailabilityType = .available,
        note: String? = nil,
        source: AvailabilitySource? = nil
    ) {
        self.id = id
        self.start = start
        self.end = end
        self.type = type
        self.note = note
        self.source = source
    }

    // Custom Codable for backward compatibility with existing JSON files
    // that don't have type/note/source fields.
    enum CodingKeys: String, CodingKey {
        case id, start, end, type, note, source
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(UUID.self, forKey: .id)
        start = try container.decode(Date.self, forKey: .start)
        end = try container.decode(Date.self, forKey: .end)
        type = try container.decodeIfPresent(AvailabilityType.self, forKey: .type) ?? .available
        note = try container.decodeIfPresent(String.self, forKey: .note)
        source = try container.decodeIfPresent(AvailabilitySource.self, forKey: .source)
    }
}

extension AvailabilitySlot {
    func contains(start: Date, end: Date) -> Bool {
        return self.start <= start && self.end >= end
    }
}

extension [AvailabilitySlot] {
    func exists(on day: Date) -> Bool {
        self.contains { Calendar.current.isDate($0.start, inSameDayAs: day) }
    }
}
