//
//  AvailabilityEntry.swift
//  AthleticsPerformance
//
//  Created by Frank Ufer on 12.04.25.
//

import Foundation

/// Represents a single availability entry for a therapist, including the type and time period.
struct AvailabilityEntry: Identifiable, Codable, Hashable {
    /// Unique identifier for the availability entry.
    var id: UUID

    /// Identifier of the therapist to whom this entry belongs.
    var therapistId: UUID

    /// Start date and time of the availability period.
    var startDate: Date

    /// End date and time of the availability period.
    var endDate: Date

    /// Type of availability (e.g., available, vacation, training, blocked).
    var type: AvailabilityType

    /// Optional note or comment for this entry.
    var note: String?

    /// Optional source information (e.g., manually created, generated by rule).
    var source: AvailabilitySource?

    enum CodingKeys: String, CodingKey {
        case id, therapistId, startDate, endDate, type, note, source
    }

    /// Initializer with default UUID
    init(
        id: UUID = UUID(),
        therapistId: UUID,
        startDate: Date,
        endDate: Date,
        type: AvailabilityType,
        note: String? = nil,
        source: AvailabilitySource? = nil
    ) {
        self.id = id
        self.therapistId = therapistId
        self.startDate = startDate
        self.endDate = endDate
        self.type = type
        self.note = note
        self.source = source
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(UUID.self, forKey: .id)
        therapistId = try decodeTherapistId(from: container, forKey: .therapistId)
        startDate = try container.decode(Date.self, forKey: .startDate)
        endDate = try container.decode(Date.self, forKey: .endDate)
        type = try container.decode(AvailabilityType.self, forKey: .type)
        note = try container.decodeIfPresent(String.self, forKey: .note)
        source = try container.decodeIfPresent(AvailabilitySource.self, forKey: .source)
    }
}

/// Enum representing the type of availability for a time slot.
enum AvailabilityType: String, CaseIterable, Identifiable, Codable {
    /// Therapist is available for appointments.
    case available

    /// Therapist is on vacation.
    case vacation

    /// Therapist is in training or continuing education.
    case training

    /// Therapist is blocked (not available for other reasons).
    case blocked

    /// Unique identifier for the availability type (required for Identifiable protocol).
    var id: String { self.rawValue }

    /// Localized label for the availability type.
    var label: String {
        switch self {
        case .available: return "Verfügbar"
        case .vacation: return "Urlaub"
        case .training: return "Fortbildung"
        case .blocked: return "Geblockt"
        }
    }
}

/// Enum indicating the source of an availability entry.
enum AvailabilitySource: String, Codable {
    /// Manually entered by a user.
    case manual

    /// Generated based on rules or recurring patterns.
    case ruleBased

    /// Entry is due to a public holiday.
    case holiday

    /// Entry is due to vacation.
    case vacation

    /// Entry is due to training or continuing education.
    case training
}

